sonar.projectKey=aceest-fitness
sonar.projectName=ACEest Fitness
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=venv/**,test_app.py,**/__pycache__/**
sonar.python.coverage.reportPaths=test-results/coverage.xml
sonar.python.xunit.reportPath=test-results/junit.xml